"""full_models_fixed

Revision ID: 466e83473c2b
Revises: 2748d6c9b4b4
Create Date: 2025-10-02 13:41:14.452685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '466e83473c2b'
down_revision: Union[str, Sequence[str], None] = '2748d6c9b4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_status_transition',
                    sa.Column('from_status',
                              sa.Enum('pending', 'active', 'finished', 'cancelled', name='appointmentstatus'),
                              nullable=False),
                    sa.Column('to_status',
                              sa.Enum('pending', 'active', 'finished', 'cancelled', name='appointmentstatus'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('from_status', 'to_status')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_status_transition')
    # ### end Alembic commands ###
