"""user:role + specialty

Revision ID: 69ed78f0093a
Revises: b1e47a49dfda
Create Date: 2025-09-21 11:25:33.500526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '69ed78f0093a'
down_revision: Union[str, Sequence[str], None] = 'b1e47a49dfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='role'), nullable=False),
                    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('specialty_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['specialty_id'], ['specialty.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
