"""user:role + specialty

Revision ID: 9870d2e36b11
Revises: b1e47a49dfda
Create Date: 2025-09-21 10:59:10.342269

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9870d2e36b11'
down_revision: Union[str, Sequence[str], None] = 'b1e47a49dfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialty',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('descripition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='role'), nullable=False),
                    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('specialty_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['specialty_id'], ['specialty.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('specialty')
    # ### end Alembic commands ###
