"""created_at and description change

Revision ID: c77f25c1a68d
Revises: e61069e2e094
Create Date: 2025-09-30 09:41:18.392099

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77f25c1a68d'
down_revision: Union[str, Sequence[str], None] = 'e61069e2e094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialty', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('specialty', 'descripition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialty', sa.Column('descripition', sa.VARCHAR(), nullable=True))
    op.drop_column('specialty', 'description')
    # ### end Alembic commands ###
